DROP SCHEMA Rhosegold;
CREATE SCHEMA Rhosegold;
USE Rhosegold;

CREATE TABLE Brukere (
Epost CHAR(100),
Passord CHAR(100),
Adresse VARCHAR(100),
Add_Adresse VARCHAR(100),
Navn VARCHAR(100),
Postnr VARCHAR(4),
Poststed VARCHAR(100)
);

CREATE TABLE Kategorier (
KategoriNavn VARCHAR(50) NOT NULL PRIMARY KEY
);

INSERT INTO Kategorier VALUES ('Lip Gloss');
INSERT INTO Kategorier VALUES ('Lashes');
INSERT INTO Kategorier VALUES ('Holiday Collection');
INSERT INTO Kategorier VALUES ('Juicy Collection');
INSERT INTO Kategorier VALUES ('Original Collection');
INSERT INTO Kategorier VALUES ('Valentine Collection');
INSERT INTO Kategorier VALUES ('RhoseGold x Meraki');

CREATE TABLE Produkter (
ProduktNavn VARCHAR(30),
ProduktId CHAR(6) PRIMARY KEY,
Beskrivelse VARCHAR(2000),
Ingredienser VARCHAR(2000),
Pris DECIMAL,
Kategori VARCHAR(50)
);

INSERT INTO Produkter VALUES('Cinnamon', '123456', 'Cinnamon is a brown tinted lip gloss that will enhance your natural lip color. Its perfect for those who love clear gloss. The gloss is infused with moisturizing oils and a blend of vitamin E. Vanilla scented and flavoured. Wand tube: 6 ml, Squeeze tube: 10 ml', 'Hydrogenated Polyisobutene (and) Ethylene/Propylene/Styrene Copolymer (and) Butylene/Ethylene/Styrene Copolymer, Caprylic/Capric Triglyceride, Sweet Almond Oil, Vitamin E, Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Flavouring Oil, Coconut Oil, Castor Oil, Iron Oxide (77499) (77491) (77492) (77891). ', 80.0,'Lip Gloss, Holiday Collection');
INSERT INTO Produkter VALUES('Crystal', '213467', 'Clear gloss with butterflies, infused with moisturizing oils and a blend of vitamin E. Peppermint scented and flavoured to give a plumping effect. Wear with your lip liner, lipstick or alone. Wand Tube: 6 ml, Squeeze Tube: 10 ml', 'Hydrogenated Polyisobutene, Ethylene/Propylene/Styrene Copolymer, Butylene/Ethylene/Styrene Copolymer, Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Hydrogenated Polyisobutene, Caprylic/Capric Triglyceride, Vitamin E, Peppermint Flavouring Oil', 80.0,'Lip Gloss, Original Collection');
INSERT INTO Produkter VALUES('Mercury', '313468', 'Meraki X RhoseGold Handmade, fluffy and reusable mink lashes.Mercury Lashes - Will add intensity to your makeup and create a feminine doll eyed look.', '', 130.0, 'Lashes, RhoseGoldxMeraki');
INSERT INTO Produkter VALUES('Trio Set', '413469', 'The Trio Set - 3 lip glosses from our Original Collection! This bundle includes Crystal - a clear gloss, peppermint scented to give a plumping effect. Our best seller! Brown Sugar - a sheer light brown gloss with gold shimmer Diamond - pearl, white and gold shimmery gloss', '', 200.0,'Lip Gloss, Bundle, Original Collection');
INSERT INTO Produkter VALUES('Lip & Eye Bundle', '513462', 'Lip & Eye Bundle to give you the perfect look! Create your own bundle by choosing one of our lip gloss shades and eyelashes. The lip gloss will come in squeeze tube or wand tube - depending on availability', '', 185.0, 'Lashes, RhoseGoldxMeraki, Bundle');
INSERT INTO Produkter VALUES('Holiday Bundle', '213464', 'The Holiday Bundle is the perfect gift for your friends, sisters, or maybe for yourself? Our new glosses consist of glitters, shimmers and beautiful colors. The Holiday Bundle includes our new glosses: Naughty, Cinnamon, 24 Karat, Frosy', '', 285.0,'Lip Gloss, Bundle, Holiday Collection');
INSERT INTO Produkter VALUES('Juicy Duo', '113463', 'Pigment glosses from the Juicy Collection. ', 'Juicy Duo includes: Lil Baby is a pink gloss with a hint of gold shimmer, Peachie is a coral orange gloss', 150.0,'Lip Gloss, Bundle, Juicy Collection');
INSERT INTO Produkter VALUES('Majestic', '813467', 'Meraki X RhoseGold Handmade, fluffy and reusable mink lashes.Majestic Lashes - Fluffy and fierce, perfect for achieving a glamorous look.', '', 130.0,'Lashes, RhoseGoldxMeraki');
INSERT INTO Produkter VALUES('Diamond', '993463', 'Pearl, white and gold shimmery gloss. Infused with moisturizing oils and vitamin E. Mixed Berry scented and flavoured. Wand tube: 6 ml, Squeeze tube: 10 ml', 'Hydrogenated Polyisobutene, Ethylene/Propylene/Styrene Copolymer, Butylene/Ethylene/Styrene Copolymer, Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Hydrogenated Polyisobutene, Caprylic/Capric Triglyceride, Sweet Almond Oil, Vitamin E, Flavouring Oil, Castor Oil, Titanium Dioxide (77891), Polyethylene Terephalate, Aluminum, Polyurethane 33, Synthetic Fluorphlogopite, Silica (SiO2), Titanium Dioxide (77891), Tin Oxide (77861).', 80.0,'Lip Gloss, Original Collection');
INSERT INTO Produkter VALUES('Brown Sugar', '703464', 'Sheer light brown gloss with gold shimmer, infused with moisturizing oils and a blend of vitamin E. Vanilla scented and flavoured. Wand tube: 6 ml, Squeeze tube: 10 ml ', 'Hydrogenated Polyisobutene (and) Ethylene/Propylene/Styrene Copolymer (and) Butylene/Ethylene/Styrene Copolymer,  Caprylic/Capric Triglyceride, Sweet Almond Oil, Vitamin E, Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Flavouring Oil, Coconut Oil, Castor Oil, Iron Oxide (77499) (77491) (77492), Synthetic Fluorphlogopite, Silica (SiO2), Titanium Dioxide (77891), Tin Oxide (77861).', 80.0,'Lip Gloss, Original Collection');
INSERT INTO Produkter VALUES('Frosty', '503463', 'Frosty is a glitter gloss with blue and purple glitter. It appears clear yet shimmery, and is perfect for the holidays. The gloss is infused with moisturizing oils and a blend of vitamin E. Mixed Berry scented and flavoured. Wear it with your lip liner, your favorite lip stick or even alone! Frosty is beautiful. Wand tube: 6 ml, Squeeze tube: 10 ml', 'Hydrogenated Polyisobutene (and) Ethylene/Propylene/Styrene Copolymer (and) Butylene/Ethylene/Styrene Copolymer, Caprylic/Capric Triglyceride, Sweet Almond Oil, Vitamin E, Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Flavouring Oil, Coconut Oil, Calcium Sodium Borosilicate, Tin Oxide (778161), Synthetic Fluorphlogopite, Titanium Dioxide (77891),Silica, Ferric Ferrocyanide (77510).', 80.0,'Lip Gloss, Holiday Collection');
INSERT INTO Produkter VALUES('Muse', '603465', 'Meraki X RhoseGold Handmade, fluffy and reusable mink lashes.Muse Lashes - Will give you a natural look. She is extremely cute and pretty. ', '', 130.0, 'Lashes, RhoseGoldxMeraki');
INSERT INTO Produkter VALUES('Rhose', '803464', 'Sheer pink gloss with beautiful glitters, infused with moisturizing oils and a blend of vitamin E. Strawberry scented and flavoured. Wand tube: 6 ml, Squeeze tube: 10 ml', 'Hydrogenated Polyisobutene, Ethylene/Propylene/Styrene Copolymer, Butylene/Ethylene/Styrene Copolymer, Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Hydrogenated Polyisobutene, Caprylic/Capric Triglyceride, Sweet Almond Oil, Vitamin E, Strawberry Flavouring Oil, Mica (77019), Titanium Dioxide (77891), Red #30 (73360), Tin Oxide (778161), Calcium Aluminum Borosilicate, Amorphous Silica, Titanium Dioxide, Tin Oxide, Polyethylene Terephthalate, Aluminum, Epoxy Copolymer, Castor Oil, Tocopheryl Acetate (Vitamin E), Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Titanium Dioxide (CI 77891).', 80.0,'Lip Gloss, Original Collection');
INSERT INTO Produkter VALUES('Peachie', '663465', 'A pretty coral orange gloss, infused with moisturizing oils and a blend of vitamin E. Peachie is strawberry scented and flavoured. Available in Squeeze Tubes and Wand Tubes.', 'Hydrogenated Polyisobutene (and) Ethylene/Propylene/Styrene Copolymer (and) Butylene/Ethylene/Styrene Copolymer,  Caprylic/Capric Triglyceride, Sweet Almond Oil, Vitamin E, Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Flavouring Oil, Coconut Oil, Castor Oil, Red 30 (73360), Orange 5 (45370), Tocopheryl Acetate (Vitamin E), Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Titanium Dioxide (CI 77891). May Contain: Iron Oxides (CI 77491) (CI 77499) (CI 77492), Red 7 Lake (CI 16255), Red 6 Lake (CI 15850), Red 30 Lake (CI 73360), Red 40 Lake (CI 16035), Red 21 Lake (CI 45380:2), Yellow 5 Lake (CI 19140), Yellow 6 Lake (CI 15985), Orange 5 Lake (CI 45370).', 80.0, 'Lip Gloss, Juicy Collection');
INSERT INTO Produkter VALUES('Flarez', '113468', 'Meraki X RhoseGold Handmade, fluffy and reusable mink lashes.Flarez Lashes - Stunning lashes that have differing lengths. She is lightweight, pretty and flattering.', '', 130.0, 'Lashes, RhoseGoldxMeraki');
INSERT INTO Produkter VALUES('Lil Baby', '443478', 'A pretty pink gloss with a hint of shimmer, infused with moisturizing oils and a blend of vitamin E. Lil Baby is strawberry scented and flavoured. Available in Squeeze Tubes and Wand Tubes.', 'Hydrogenated Polyisobutene (and) Ethylene/Propylene/Styrene Copolymer (and) Butylene/Ethylene/Styrene Copolymer,  Caprylic/Capric Triglyceride, Sweet Almond Oil, Vitamin E, Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Flavouring Oil, Coconut Oil, Castor Oil, Tocopheryl Acetate (Vitamin E), Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Titanium Dioxide (CI 77891), Orange 5 (45370), Red 30 (73360), Aluminum Calcium Sodium Silicate, Titanium Dioxide (77891), Tin Oxide (77861),Red 7 Ca Lake (15850).', 80.0, 'Lip Gloss, Juicy Collection');
INSERT INTO Produkter VALUES('24 karat', '743379', '24 Karat is a holographic glitter gloss that will give your lips a glowy and a "rainbow" effect. 24 Karat is packed with gold shimmer and gold holographic glitter. The gloss is infused with moisturizing oils and a blend of vitamin E. Vanilla scented and flavoured. Wand tube: 6 ml, Squeeze tube: 10 ml', 'Hydrogenated Polyisobutene (and) Ethylene/Propylene/Styrene Copolymer (and) Butylene/Ethylene/Styrene Copolymer, Caprylic/Capric Triglyceride, Sweet Almond Oil, Vitamin E, Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Flavouring Oil, Coconut Oil, Mica (77019), Titanium Dioxide (77891), Iron Oxide (77491), Polyethylene Terephalate, Aluminum, Polyurethane 33, Pigment.', 80.0, 'Lip Gloss, Holiday Collection');
INSERT INTO Produkter VALUES('Sugarplum', '663472', 'Sugar Plum is a beautiful plum gloss, infused with moisturizing oils and a blend of vitamin E. Mixed berry scented and flavoured. The gloss is buildable, creamy and non-sticky. Available in Wand Tubes. ', 'Hydrogenated Polyisobutene (and) Ethylene/Propylene/Styrene Copolymer (and) Butylene/Ethylene/Styrene Copolymer,  Caprylic/Capric Triglyceride, Sweet Almond Oil, Vitamin E, Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Flavouring Oil, Coconut Oil, Castor Oil, Tocopheryl Acetate (Vitamin E), Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Titanium Dioxide (CI 77891), Orange 5 (45370), Red 30 (73360), Aluminum Calcium Sodium Silicate, Titanium Dioxide (77891), Tin Oxide (77861), Red 7 Ca Lake (15850), Iron Oxide (77499) (77491) (77492), Titanium Dioxide (CI 77891).', 80.0, 'Lip Gloss, Valentine Collection');
INSERT INTO Produkter VALUES('Euphoria', '773463', 'Meraki X RhoseGold Handmade, fluffy and reusable mink lashes.Euphoria Lashes - Sexy and dramatic. Perfect going out lashes. The length and volume gradually increase giving you a slanted feel.', '', 130.0, 'Lashes, RhoseGoldxMeraki');
INSERT INTO Produkter VALUES('Valentine Bundle', '223435', 'Lip glosses from The Valentines Day Collection. Valentine Bundle includes: 14 - Mauve pink gloss, Sugar Plum - Purple plum gloss' , '', 150.0, 'Bundle, Lip Gloss, Valentine Collection');
INSERT INTO Produkter VALUES('Naughty', '763592', 'Naughty is a red tinted lip gloss that will enhance your natural lip color.  The red color is poppin and beautiful! Its perfect for those who love clear glosses. The gloss is infused with moisturizing oils and a blend of vitamin E. Strawberry scented and flavoured. Wand tube: 6 ml, Squeeze tube: 10 ml', 'Hydrogenated Polyisobutene (and) Ethylene/Propylene/Styrene Copolymer (and) Butylene/Ethylene/Styrene Copolymer, Caprylic/Capric Triglyceride, Sweet Almond Oil, Vitamin E, Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Flavouring Oil, Coconut Oil, Red 30 (73360), Red 21 (45380).', 80.0, 'Lip Gloss, Holiday Collection');
INSERT INTO Produkter VALUES('14', '111592', 'A pretty maybe pink gloss with a hint of shimmer, infused with moisturizing oils and a blend of vitamin E. "14" is strawberry scented and flavoured. The gloss is buildable, creamy and non-sticky. Available in Wand Tubes. ', 'Hydrogenated Polyisobutene (and) Ethylene/Propylene/Styrene Copolymer (and) Butylene/Ethylene/Styrene Copolymer,  Caprylic/Capric Triglyceride, Sweet Almond Oil, Vitamin E, Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Flavouring Oil, Coconut Oil, Castor Oil, Tocopheryl Acetate (Vitamin E), Caprylyl Glycol, Phenoxyethanol, Hexylene Glycol, Titanium Dioxide (CI 77891), Orange 5 (45370), Red 30 (73360), Aluminum Calcium Sodium Silicate, Titanium Dioxide (77891), Tin Oxide (77861), Red 7 Ca Lake (15850), Iron Oxide (77499) (77491) (77492), Titanium Dioxide (CI 77891).', 80.0, 'Lip Gloss, Valentine Collection');


SELECT * FROM Produkter;
